export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const USER_ADMIN = "USER_ADMIN";
export const RESET_USER_ADMIN = "RESET_USER_ADMIN";